### ISSUE TITLE
May SysBusUsbDevice implements Parcelable?

### ISSUE THREAD

**Issue by jp1017** [alt236/USB-Device-Info---Android#19]
I using aidl, so SysBusUsbDevice implements Parcelable is necessary.

**Comment by alt236** [comment]
I am afraid not, as from version 2.0.0 the library is a standard Java library and not an Android one.

It is Serializable though, so can't you wrap it in a custom Parcelable class, which wil parcel the wrapped SysBusUsbDevice as a Serializable and pass it over?

**Comment by jp1017** [comment]
yes, thanks. :smile:
